export const WELCOME = "WELCOME"; // Welcome Screen
export const NEW = "NEW"; // Create new Room
export const SETTINGS = "SETTINGS"; // Create new Room
export const JOIN = "JOIN"; // Create new Room
export const NAME = "NAME"; // Add name to existing room
export const WAITING = "WAITING"; // Waiting Room
export const PLAY = "PLAY"; // Questions
export const SCOREBOARD = "SCOREBOARD"; // Score Board
export const NOTIF_TIMEOUT = 4000; // in ms
